# Generated by Django 4.2.1 on 2023-07-19 09:58

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cond', models.CharField(max_length=25)),
                ('prenom_cond', models.CharField(max_length=50)),
                ('contact_cond', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TG')),
            ],
        ),
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=13)),
                ('couleur', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_grade', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InfoEngin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=30)),
                ('consommation', models.FloatField()),
                ('vidange', models.FloatField()),
                ('revision', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEngin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('nombre_roue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_maintenance', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VidangeEngin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vidange', models.DateField()),
                ('engin_vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.engin')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(max_length=25)),
                ('prenom_user', models.CharField(max_length=50)),
                ('contact_user', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='TG')),
                ('email_user', models.EmailField(max_length=254)),
                ('motDePasse', models.CharField(max_length=12)),
                ('grade_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.grade')),
            ],
        ),
        migrations.CreateModel(
            name='ReleveDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateField()),
                ('nbKmDebut', models.FloatField()),
                ('nbKmFin', models.FloatField()),
                ('engin_releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.engin')),
            ],
        ),
        migrations.CreateModel(
            name='RavitaillementCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ravitaillement', models.DateField()),
                ('quantite', models.FloatField()),
                ('engin_rav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.engin')),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=20)),
                ('annee', models.SmallIntegerField()),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.marque')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceEngin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_maintenance', models.DateField()),
                ('motif_maintenance', models.CharField(max_length=120)),
                ('engin_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.engin')),
                ('type_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.typemaintenance')),
            ],
        ),
        migrations.AddField(
            model_name='engin',
            name='info_engin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.infoengin'),
        ),
        migrations.AddField(
            model_name='engin',
            name='modele_engin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.modele'),
        ),
        migrations.AddField(
            model_name='engin',
            name='type_engin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.typeengin'),
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateField()),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.conducteur')),
                ('engin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.engin')),
            ],
        ),
    ]
